title: "My Name"
description: "Welcome to my website"

# Load theme from GitHub repository
remote_theme: mmistakes/minimal-mistakes

# Required plugin to render remote themes on GitHub Pages
plugins:
  - jekyll-remote-theme
