title: "Ziheng Yu"

# Load theme from GitHub repository
remote_theme: "academicpages/academicpages.github.io"

author:
  name             : "Ziheng Yu"
  avatar           : "/Ziheng_Yu.jpg" # Path to your photo
  bio              : "Ph.D. Candidate in Economics at the University of Texas at Austin."
  location         : "Austin, TX, USA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ziheng.yu@utexas.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Yu-ZiHeng"
      
# 指定使用 _data/navigation.yml 里的 main 导航栏
main:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /CV.pdf

# 必需插件
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
