title: "Ziheng Yu"

# Load theme from GitHub repository
remote_theme: "mmistakes/minimal-mistakes"

# Choose a skin/color scheme (e.g., default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise)
minimal_mistakes_skin: "default"

# Required plugins for GitHub Pages and Minimal Mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
